# Generated by Django 4.0.3 on 2022-03-01 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial_1'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userprofiledetails',
            unique_together=set(),
        ),
    ]
