# Generated by Django 4.0.2 on 2022-02-27 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofiledetails',
            table='user_profile_details',
        ),
    ]
