# Generated by Django 4.0.2 on 2022-02-27 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_employee_app', '0002_rename_emp_id_employee_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='user',
            new_name='emp',
        ),
    ]
